### ISSUE TITLE
Map Index Assignment: no prefix parse function for = found

### ISSUE THREAD

**Issue by duckbrain** [gobuffalo/plush#116]
Plush doesn't seem to support assigning to map indexes.

```go
package main

import (
	"github.com/gobuffalo/plush"
)

func run(s string) {
	ctx := plush.NewContext()
	err := plush.RunScript(s, ctx)
	if err != nil {
		panic(err)
	}
}

func main() {
	run(`
	let a = "hello"
	println(a)
	a = "world"
	println(a)
	`)
	run(`
	let a = "Hello"
	let b = {}
	b[a] = "world"
	println(b)
	`)
}
```

```
~/tmp 1 $ go run main.go
hello
world
panic: line 4: no prefix parse function for = found

goroutine 1 [running]:
main.run(0x7f84a2, 0x3b)
	/home/jonathan/tmp/main.go:11 +0x85
main.main()
	/home/jonathan/tmp/main.go:22 +0x4f
exit status 2
```

**Comment by Mido-sys** [comment]
@duckbrain 

Sent a [pull request #129](https://github.com/gobuffalo/plush/pull/129). The new pull request will allow map and array assignment.

**Comment by paganotoni** [comment]
Merged. Closing this issue. Thanks again @Mido-sys
